version: "3"

services:
  sample-back:
    container_name: sample-back
    networks:
      default:
      reverse-proxy-network:
        aliases:
          - sample-back-container
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3001:3000"
      - "5555:5555"
    volumes:
      - ./src:/work
    tty: true
    restart: always
    depends_on:
      - sample-back-db

  sample-back-db:
    container_name: sample-back-db
    networks:
      default:
      reverse-proxy-network:
        aliases:
          - sample-back-db-container
    image: postgres:15.3-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - "./db-data:/var/lib/postgresql/data"
    ports:
      - "5433:5432"
    tty: true
    restart: always

networks:
  reverse-proxy-network:
    external: true